odimra:
  redisImageTag: "3.0"
  namespace:
  groupID:
  redisOndiskDataPath:
  redisInmemoryDataPath:
  redisSecondayReplicaCount: 2
  redisMasterSet: primaryset
  redisQuorum: 2
  redisDownAfterMilliseconds: 60000
  redisFailoverTimeout: 60000
  redisParallelSyncs: 1
  redisInMemoryPassword:
  redisOnDiskPassword:
